repos:
  - repo: https://github.com/trim21/dprint-pre-commit
    rev: v0.49.1
    hooks:
      - id: dprint
        types_or:
          - json
          - toml
          - yaml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: fix-byte-order-marker
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-added-large-files # check for file bigger than 500kb
      - id: debug-statements
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-format
